package vn.greenlab.model.enums;

public enum ErrorCode {
    // ===== Auth =====
    LOST_PASSWORD_CODE_EXPIRED("Mã khôi phục mật khẩu đã hết hạn", "Lost password code expired"),
    CONFIRM_PASSWORD_NOT_MATCH("Mật khẩu xác nhận không khớp", "Confirm password not match"),
    INVALID_PASSWORD("Mật khẩu không hợp lệ", "Invalid password"),
    LOST_PASSWORD_CODE_NOT_FOUND("Mã khôi phục mật khẩu không tồn tại", "Lost password code not found"),
    EMAIL_EMPTY("Email không được để trống", "Email must not be empty"),
    NO_RESULT_TO_PRINT("Bệnh nhân không có kết quả để in", "Patient does not have results to print"),
    START_BARCODE_ALREADY_EXISTS("Mã barcode đã tồn tại", "Start barcode already exists"),
    IMAGE_UPLOAD_FAILED("Lỗi khi tải ảnh lên", "Image upload failed"),
    PLEASE_SELECT_DOCTOR_BEFORE_INSERT_RESULT("Vui lòng chọn bác sĩ trước khi thêm chỉ định", "Please select doctor before inserting result"),
    PROFILE_NOT_FOUND("Hồ sơ không tồn tại", "Profile not found"),
    SHIPPING_RESULT_NOT_FOUND("Thông tin chuyển phát không tồn tại", "Shipping result not found"),
    PHONE_EMPTY("Số điện thoại không được để trống", "Phone must not be empty"),
    PRICE_POLICY_CODE_ALREADY_EXISTS("Mã chính sách giá đã tồn tại", "Price policy code already exists"),
    PRICE_POLICY_IDS_EMPTY("Danh sách chính sách giá không được để trống", "Price policy IDs must not be empty"),
    PRICE_POLICY_CODE_EMPTY("Mã chính sách giá không được để trống", "Price policy code must not be empty"),
    PRICE_POLICY_NAME_EMPTY("Tên chính sách giá không được để trống", "Price policy name must not be empty"),
    FROM_TIME_EMPTY("Thời gian bắt đầu không được để trống", "From time must not be empty"),
    TO_TIME_EMPTY("Thời gian kết thúc không được để trống", "To time must not be empty"),
    PRICE_POLICY_NOT_FOUND("Chính sách giá không tồn tại", "Price policy not found"),
    PRICE_POLICY_TEST_NOT_FOUND("Chính sách giá theo XN không tồn tại", "Price policy test not found"),
    PROCESS_ALREADY_CANCELLED("Địa chỉ địa chỉ đã bị hủy", "Address already cancelled"),
    DELIVERY_NOTE_NOT_HAVE_PATIENT_INFO("Phiếu không có thông tin bệnh nhân", "Delivery note does not have patient info"),
    PHONE_ALREADY_EXISTS("Số điện thoại đã tồn tại", "Phone number already exists"),
    EMAIL_ALREADY_EXISTS("Email đã tồn tại", "Email already exists"),
    USERNAME_ALREADY_EXISTS("Tên đăng nhập đã tồn tại", "Username already exists"),
    WRONG_PASSWORD("Sai mật khẩu", "Incorrect password"),
    PASSWORD_NEW_EMPTY("Mật khẩu mới không được để trống", "New password must not be empty"),
    RESULT_PRINT_NOT_FOUND("Kết quả in không tồn tại", "Result print not found"),
    NOT_HAVE_ANY_MISS_CALL("Không có cuộc gọi nhỡ nào", "No missed call found"),
    ACCOUNT_NOT_EXISTS("Tài khoản không tồn tại", "Account does not exist"),
    ACCOUNT_LOCKED("Tài khoản đã bị khóa. Vui lòng liên hệ quản trị viên", "Account is locked. Please contact admin"),
    ADMIN_NOT_FOUND("Nhân viên không tồn tại", "Employee not found"),
    NOT_HAVE_PERMISSION("Bạn không có quyền thực hiện chức năng này",
            "You do not have permission to perform this action"),
    DEFAULT("Đã có lỗi xảy ra, vui lòng thử lại", "An error occurred, please try again"),
    DEPARTMENT_NOT_FOUND("Phòng ban không tồn tại", "Department not found"),
    SPECIALIST_NOT_FOUND("Danh mục chuyên khoa không tồn tại", "Specialist not found"),
    SPECIALIST_ID_ALREADY_EXISTS("ID danh mục chuyên khoa đã tồn tại", "Specialist ID already exists"),
    SPECIALIST_NAME_ALREADY_EXISTS("Tên danh mục chuyên khoa đã tồn tại", "Specialist name already exists"),
    LABORATORY_NOT_FOUND("Nơi gửi thí nghiệm không tồn tại", "Laboratory not found"),
    LABORATORY_CODE_ALREADY_EXISTS("Mã nơi gửi thí nghiệm đã tồn tại", "Laboratory code already exists"),
    CFG_TEST_NOT_FOUND("Xét nghiệm không tồn tại", "Test not found"),
    RETURN_TIME_NOT_FOUND("Thời gian hẹn trả không tồn tại", "Return time not found"),
    RETURN_TIME_EXISTS("Đã có thời gian hẹn trả với cặp mã dịch vụ và mã xét nghiệm",
            "Return time already exists with this service and test code"),
    NORMAL_RANGE_NOT_FOUND("Chỉ số bình thường không tồn tại", "Normal range not found"),
    NORMAL_RANGE_TEST_CODE_NOT_FOUND("Mã xét nghiệm không tồn tại trong CfgTest", "Test code not found in CfgTest"),
    CFG_TEST_INSTRUMENT_NOT_FOUND("Xét nghiệm theo máy không tồn tại", "Instrument test not found"),
    CFG_TEST_INSTRUMENT_TEST_CODE_NOT_FOUND("Mã xét nghiệm không tồn tại trong CfgTest",
            "Instrument test code not found in CfgTest"),
    INVALID_SUM_PERTAGE_FORMAT("Tỷ lệ phần trăm phải lớn hơn 0 và nhỏ hơn 100.", "Sum percentage must be greater than 0 and less than 100."),
    INVALID_SUM_TRANSPORT_FORMAT("Số tiền đi lại phải lớn hơn 0.", "Transport cost must be greater than 0."),
    INSTRUMENT_NOT_FOUND("Máy xét nghiệm không tồn tại", "Instrument not found"),
    INSTRUMENT_CODE_ALREADY_EXISTS("Mã máy xét nghiệm đã tồn tại", "Instrument code already exists"),
    INSTRUMENT_ADMIN_NOT_FOUND("Phân công máy cho nhân viên không tồn tại", "Instrument admin not found"),
    INSTRUMENT_ADMIN_ALREADY_EXISTS("Nhân viên đã được phân công cho máy này", "Instrument admin already exists"),
    RESULT_IMAGE_NOT_FOUND("Ảnh kết quả không tồn tại", "Result image does not exist"),
    RESULT_IMAGE_NAME_EMPTY("Tên ảnh kết quả không được để trống", "Result image name must not be empty"),
    USER_NOT_EXISTS("Người dùng không tồn tại", "User does not exist"),
    USERNAME_CANNOT_BE_EMPTY("Tên người dùng không được để trống", "Full name cannot be empty"),
    DOCTOR_NOT_FOUND("Bác sĩ không tồn tại", "Doctor not found"),
    PATIENTS_NOT_FOUND("Hồ sơ bệnh nhân không tồn tại", "Patients not found"),
    CITY_NOT_FOUND("Thành phố không tồn tại", "City not found"),
    DISTRICT_NOT_FOUND("Quận/Huyện không tồn tại", "District not found"),
    WARD_NOT_FOUND("Phường/Xã không tồn tại", "Ward not found"),
    FILE_EMPTY("File không được để trống", "File cannot be empty"),
    FILE_NOT_IMAGE("File phải là hình ảnh", "File must be an image"),
    ADDRESS_REQUIRED("Địa chỉ không được để trống", "Address must not be empty"),
    PARTNER_TYPE_BS_CTV("Phân loại BS/CTV", "Partner Type must not be empty."),

    SYSTEM_CONFIG_NOT_FOUND("Cấu hình không tồn tại.", "Configuration does not exist."),

    // ===== CfgTestCategory =====
    CATEGORY_INVALID("Nhóm xét nghiệm không hợp lệ.", "Test category is invalid."),
    CATEGORY_ID_EMPTY("ID nhóm xét nghiệm không được để trống.", "Category ID must not be empty."),
    CATEGORY_NAME_EMPTY("Tên nhóm xét nghiệm không được để trống.", "Category name must not be empty."),
    PRINT_ORDER_INVALID("Thứ tự in phải lớn hơn hoặc bằng 1.", "Print order must be greater than or equal to 1."),
    PRINT_ORDER_2_INVALID("Thứ tự in 2 phải lớn hơn hoặc bằng 1.", "Print order 2 must be greater than or equal to 1."),
    CATEGORY_ALREADY_EXISTS("Mã nhóm xét nghiệm đã tồn tại.", "Test category code already exists."),
    CATEGORY_NOT_FOUND("Nhóm xét nghiệm không tồn tại.", "Test category does not exist."),


    // ===== CfgTest =====
    TEST_CODE_EMPTY("Mã xét nghiệm không được để trống.", "Test code must not be empty."),
    TEST_ID_EMPTY("ID xét nghiệm không được để trống.", "Test Id must not be empty."),
    TEST_NAME_EMPTY("Tên xét nghiệm không được để trống.", "Test name must not be empty."),
    TEST_PRICE_INVALID("Giá phải lớn hơn hoặc bằng 0.", "Price must be greater than or equal to 0."),
    TEST_CODE_DUPLICATED("Mã xét nghiệm này đã tồn tại.", "This test code already exists."),
    TEST_NOT_FOUND("Không tìm thấy xét nghiệm với ID %s.", "Test not found with ID %s."),

    // PrintConfigDoctorResultGroup
    PRINT_CONFIG_NOT_FOUND("Cấu hình in không tồn tại.", "Print configuration does not exist."),
    PRINT_CONFIG_ALREADY_EXISTS("Cấu hình in cho bác sĩ và nhóm kết quả này đã tồn tại.", "Print configuration for this doctor and result group already exists."),
    PRINT_CONFIG_DOCTOR_ID_EMPTY("ID bác sĩ không được để trống.", "Doctor ID must not be empty."),
    PRINT_CONFIG_RESULT_GROUP_ID_EMPTY("ID nhóm kết quả không được để trống.", "Result group ID must not be empty."),
    RESULT_GROUP_NOT_FOUND("Nhóm kết quả không tồn tại.", "Result group does not exist."),
    REPORT_TEMPLATE_TYPE_ALREADY_EXISTS("Loại biểu mẫu đã tồn tại.", "Report type already exists."),
    TEST_CODE_CONFLICT("Mã xét nghiệm mới đã tồn tại ở một xét nghiệm khác.","The new test code already exists in another test."),
    PROCESS_NOT_FOUND("Địa chỉ không tồn tại.", "Process not found."),
    DELIVERY_NOTE_NOT_FOUND("Phiếu giao nhận không tồn tại.", "Delivery note not found."),
    DELIVERY_NOTE_ALREADY_ASSIGNED("Phiếu giao nhận đã được gán cho địa chỉ khác.", "Delivery note already assigned to another process."),
    DELIVERY_NOTE_DETAIL_NOT_FOUND("Chi tiết phiếu giao nhận không tồn tại.", "Delivery note detail not found."),
    DELIVERY_NOTE_DETAIL_ALREADY_DELETED("Chi tiết phiếu giao nhận đã bị xóa.", "Delivery note detail is already deleted."),
    DELIVERY_NOTE_ID_REQUIRED("Vui lòng chọn ít nhất một phiếu giao nhận.", "Please select at least one delivery note."),
    PROCESS_TYPE_REQUIRED("Loại địa chỉ lịch hẹn không được để trống.", "Process type must not be empty."),

    // ===== DoctorDeadlineConfig =====
    DOCTOR_DEADLINE_CONFIG_NOT_FOUND("Cấu hình deadline không tồn tại.", "Deadline config not found."),
    TEST_NOT_HAVE_PROFILE("Xét nghiệm không có hồ sơ.", "Test does not have profile."),
    // ===== CfgDoctorCategory =====
    CFG_DOCTOR_CATEGORY_NOT_FOUND("Cấu hình danh mục BS/CTV không tồn tại.", "Doctor category config not found."),
    PATIENT_NOT_FOUND("Bệnh nhân không tồn tại.", "Patient not found."),
    RESULT_NOT_FOUND("Kết quả không tồn tại.", "Result not found."),

    PATIENT_RESOLVE_NOT_FOUND("Bản ghi xử lý bệnh nhân không tồn tại.", "Patient resolve record not found."),
    // ===== Doctor =====
    DOCTOR_CODE_REQUIRED("Mã bác sĩ không được để trống.", "Doctor code must not be empty."),
    PARTNER_TYPE_ID_REQUIRED("ID loại đối tác không được để trống.", "Partner type ID must not be empty."),
    CITY_ID_REQUIRED("ID thành phố không được để trống.", "City ID must not be empty."),
    DISTRICT_ID_REQUIRED("ID quận/huyện không được để trống.", "District ID must not be empty."),
    WORK_AREA_NOT_FOUND("Khu vực không tồn tại.", "Work area not found."),
    SPECIALIST_ID_REQUIRED("ID chuyên khoa không được để trống.", "Specialist ID must not be empty."),
    PARTNER_TYPE_NOT_FOUND("Loại đối tác không tồn tại.", "Partner type not found."),
    DOCTOR_CODE_ALREADY_EXISTS("Mã bác sĩ đã tồn tại.", "Doctor code already exists."),
    ID_NUMBER_ALREADY_EXISTS("Số CMND/CCCD đã tồn tại.", "ID number already exists."),
    DOCTOR_CONFIG_NOT_FOUND("Thiết lập BS/CTV không tồn tại.", "Doctor configuration not found."),
    ADMINISTRATOR_NOT_FOUND("Nhân viên không tồn tại.", "Administrator not found."),
    PARENT_DOCTOR_NOT_FOUND("Liên kết cha không tồn tại.", "Parent doctor/CTVs not found."),
    P_DOCTOR_NOT_FOUND("Đơn vị phụ trách không tồn tại.", "PDoctor not found."),
    BIRTH_DAY_OR_AGE_REQUIRED("Ngày sinh hoặc năm sinh không được để trống.", "Birth day or year of birth must not be empty."),
    PATIENT_NAME_REQUIRED("Tên bệnh nhân không được để trống.", "Patient name must not be empty."),
    PATIENT_RELATIONSHIP_REQUIRED("Quan hệ bệnh nhân không được để trống.", "Patient name must not be empty."),
    PATIENT_SEX_REQUIRED("Giới tính bệnh nhân không được để trống.", "Patient sex must not be empty."),
    PATIENT_PHONE_REQUIRED("Số điện thoại bệnh nhân không được để trống.", "Patient phone must not be empty."),
    PATIENT_PID_REQUIRED("Mã bệnh nhân không được để trống.", "Patient code must not be empty."),
    PATIENT_PID_EXISTS("Mã bệnh nhân đã tồn tại.", "Patient code exists."),
    SEX_REQUIRED("Giới tính không được để trống.", "Sex must not be empty."),
    SID_REQUIRED("Mã SID không được để trống.", "SID must not be empty."),
    INVALID_SID_FORMAT("Mã SID không hợp lệ.", "SID is invalid."),
    EXCEL_EXPORT_TIME_RANGE_REQUIRED("Cần có thời gian bắt đầu và kết thúc để xuất Excel.", "Time range is required to export Excel."),
    PLEASE_SELECT_ADMIN_REQUEST("Vui lòng chọn nhân viên yêu cầu khi thêm/xóa chỉ định sau validation.","Please select administrator request when adding/deleting designation after validation."),
    PLEASE_SELECT_ADMIN_INCHARGE("Vui lòng chọn nhân viên phụ trách khi thêm/xóa chỉ định sau validation.","Please select administrator incharge when adding/deleting designation after validation."),
    // ===== Patient =====
    PHONE_TASK_NOT_FOUND("Tư vấn gọi điện không tồn tại.", "Phone task not found."),
    IMPORT_PATIENT_BATCH_SIZE_MISMATCH("Số lượng bệnh nhân và bệnh án không khớp.", "Patient and medical record batch size mismatch."),


    // ===== Validation Errors =====
    SEARCH_TEXT_TOO_SHORT("Text tìm kiếm phải có ít nhất 3 ký tự.", "Search text must be at least 3 characters."),
    PLEASE_ENTER_SEARCH_TEXT("Vui lòng nhập text để tìm kiếm.", "Please enter text to search."),
    INVALID_SEX_FORMAT("Giới tính không hợp lệ.", "Sex is invalid."),
    INVALID_AGE_FORMAT("Tuổi không hợp lệ.", "Age is invalid."),
    PHONE_BOOK_NOT_FOUND("Số điện thoại không tồn tại trong danh bạ.", "Phone number not found in phone book."),
    INVALID_PAGE("Số trang phải lớn hơn hoặc bằng 0.", "Page number must be greater than or equal to 0."),
    INVALID_SIZE("Kích thước trang không hợp lệ.", "Page size is invalid."),
    INVALID_TIME_TYPE("Loại thời gian phải lớn hơn hoặc bằng 0.", "Time type must be greater than or equal to 0."),
    MISS_TIME_RANGE("Thời gian bắt đầu và kết thúc không được để trống.", "Missing start time and end time."),
    INVALID_NAME_FORMAT("Tên chỉ được chứa chữ cái và khoảng trắng.", "Name can only contain letters and spaces."),
    INVALID_USERNAME_FORMAT("Tên đăng nhập chỉ được chứa chữ cái, số và dấu gạch dưới.", "Username can only contain letters, numbers and underscores."),
    INVALID_CODE_FORMAT("Mã không được chứa dấu cách.", "Code must not contain spaces."),
    INVALID_PHONE_FORMAT("Số điện thoại không đúng định dạng.", "Phone number is invalid."),
    INVALID_ID_FORMAT("ID phải là số.", "ID must be a number."),
    INVALID_DATE_RANGE("Ngày bắt đầu phải nhỏ hơn hoặc bằng ngày kết thúc.", "Start date must be less than or equal to end date."),
    INVALID_DATE_FORMAT("Ngày không đúng định dạng.", "Date format is invalid."),
    INVALID_EMAIL_FORMAT("Email không đúng định dạng.", "Email format is invalid."),
    INVALID_IMAGE_FORMAT("Chỉ chấp nhận file ảnh định dạng JPG, PNG hoặc WEBP.", "Only JPG, PNG or WEBP image formats are allowed."),
    INVALID_LOG_TYPE("Loại log không hợp lệ.", "Invalid log type."),
    MAX_LENGTH_NAME_100("Họ và tên không được vượt quá 100 ký tự.", "Full name must not exceed 100 characters."),
    MAX_LENGTH_9("Mã bệnh nhân không được vượt quá 9 ký tự.", "Patient ID must not exceed 9 characters."),
    INVALID_PID_FORMAT("PID phải là dãy số gồm 8 ký tự.", "Patient ID must be 8 digits."),
    DOCTOR_ID_REQUIRED("Mã bác sĩ không được để trống.", "Doctor ID must not be empty."),
    INVALID_CMND_FORMAT("Số CMND/CCCD không đúng định dạng.", "CMND/CCCD format is invalid."),
    INVALID_ADMINISTRATOR_ID("ID quản trị viên phải là số dương.", "Administrator ID must be a positive number."),
    TEST_ALREADY_IN_PROFILE("Xét nghiệm đã tồn tại trong hồ sơ.", "Test already in profile."),
    TEST_ALREADY_IN_DOCTOR("Xét nghiệm đã tồn tại trong bác sĩ.", "Test already in doctor."),
    PROFILE_ALREADY_EXISTS("Hồ sơ đã tồn tại.", "Profile already exists."),
    RESULT_ALREADY_EXISTS("Đã có kết quả với mã xét nghiệm này.", "Result already exists with this test code."),
    PID_TOO_LONG("Mã bệnh nhân phải có độ dài 9 ký tự.", "Patient ID must be 9 characters long."),
    DELETE_RESULT_BEFORE_PATIENT("Phải xóa dịch vụ trước khi xóa khách hàng.", "Must delete result before deleting patient."),
    CANNOT_DELETE_RESULT_OVER_10_MINUTES("Đã quá thời gian cho phép xóa xét nghiệm.", "The time limit for deleting the test has expired."),
    CANNOT_DELETE_RESULT_HAS_INVOICE("Dịch vụ thu tiền. Liên hệ bộ phận sửa xóa.", "Payment service. Contact the deletion/editing department.."),
    CANNOT_DELETE_RESULT_HAS_RESULT("Dịch vụ đã chạy XN hoặc có KQ. Liên hệ bộ phận sửa xóa.", "The test has been run or has results. Contact the deletion/editing department.."),
    SID_ALREADY_EXISTS("Mã %sid đã được thêm vào sổ với khách %customerName vào ngày %date", "SID %sid already exists with customer %customerName on date %date"),
    SID_EXISTS("Mã %sid đã được vào phiếu %deliveryNote", "SID %sid already exists with delivery note %deliveryNote"),
    SUCCESS("Thành công", "Success"),
    FAIL("Thất bại", "Fail"),
    UNKNOWN_ERROR("Không tìm thấy lỗi!", "Unknown error"),
    NOT_FOUND("Không tìm thấy!", "Not found"),
    LOCATION_STORAGE_TRAY_ERROR("Khay không được để trống", "Not found"),
    LOCATION_SAMPLE_STORAGE("Vị trí trong khay đã đầy cần thêm vào khay khác", "Not found"),
    LOCATION_SAMPLE_STORAGE_EXISTS("Vị trí trong khay đã tồn tại cần thêm vào vị trí khác", "Not found"),
    PLEASE_USE_UPDATE_DOCTOR_TO_CHANGE_DOCTOR("Vui lòng sử dụng chức năng cập nhật bác sĩ để thay đổi bác sĩ khi khách đã được valid.", "Please use the update doctor function to change doctor when customer is valid."),


    ALREADY_MARKED_EMERGENCY("Bệnh nhân đã được đánh dấu cấp cứu.", "Already marked as emergency."),
    APPOINTMENT_SAMPLE_IMAGE_LIMIT_REACHED("Chỉ tải lên tối đa 5 ảnh.", "Only upload up to 5 images."),
    BAD_REQUEST("Lỗi", "Bad request"),
    TEMPLATE_MAIL_NOT_FOUND("Template email không tồn tạ(i.", "Email template not found."),

    // ===== TestResult =====
    CANNOT_UPDATE_AFTER_VALID_L2("Không thể cập nhật sau khi valid cấp 2.", "Cannot update after valid level 2."),
    CANNOT_VALID_L2_AFTER_HAVE_RESULT("Vui lòng valid cấp 1 những dòng có kết quả trước khi valid cấp 2.", "Please valid level 1 before valid level 2."),
    CANNOT_UPDATE_RESULT_BECAUSE_LOCKED("Không thể cập nhật kết quả vì đã có người dùng khác đang thao tác.", "Cannot update result because another user is performing the action."),
    ;

    private final String descriptionVi;
    private final String descriptionEn;

    ErrorCode(String vi, String en) {
        this.descriptionVi = vi;
        this.descriptionEn = en;
    }

    public String getDescription(String lang) {
        return "en".equalsIgnoreCase(lang) ? descriptionEn : descriptionVi;
    }
}
