#spring.application.name=greenlab
#server.servlet.context-path=/api-admin
#server.port=8081
#admin=1
#
#msc_user=bvnamhoc.namph,linhpt,phuonghoa,thucanh
#technician_user=DUNGNT,thuhant
#
#spring.data.mongodb.uri=mongodb://dev:1RDvrdLf@47.242.60.211:27017/greenlab
#spring.datasource.url=jdbc:mysql://14.177.64.56:33079/greenlab
#spring.datasource.username=dev
#spring.datasource.password=9VRcrdT
#
## spring.data.mongodb.uri=mongodb://localhost:27017/greenlab
## spring.datasource.url=jdbc:mysql://localhost:3307/greenlab
## spring.datasource.username=root
## spring.datasource.password=
#
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.servlet.multipart.max-file-size=10MB
#spring.servlet.multipart.max-request-size=10MB
#jwt.secret=ZmFrZVNlY3JldEtleUZvckdyZWVuTGFiMTIzNDU2Nzg5MDEyMzQ1Njc4OTA=
#jwt.expirationMs=86400000
#
#spring.data.redis.host=103.38.236.251
#spring.data.redis.port=6379
#spring.data.redis.password=NLoga41_1ABCCC123
#spring.data.redis.database=0
#spring.data.redis.timeout=3000ms
#
#permission.init=true
#spring.application.name=greenlab
#server.servlet.context-path=/api-admin
#server.port=8081
#admin=1
#msc_user=bvnamhoc.namph,linhpt,phuonghoa,thucanh
#technician_user=DUNGNT,thuhant
#spring.data.mongodb.uri=mongodb://mongodb:27017/greenlab
#spring.datasource.url=jdbc:mysql://mysql:3306/greenlab
#spring.datasource.username=dev
#spring.datasource.password=552502102
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.show-sql=false
#spring.jpa.properties.hibernate.format_sql=true
#spring.servlet.multipart.max-file-size=10MB
#spring.servlet.multipart.max-request-size=10MB
#jwt.secret=ZmFrZVNlY3JldEtleUZvckdyZWVuTGFiMTIzNDU2Nzg5MDEyMzQ1Njc4OTA=
#jwt.expirationMs=86400000
#
#spring.data.redis.host=redis
#spring.data.redis.port=6379
#spring.data.redis.password=NLoga41_1ABCCC123
#spring.data.redis.database=0
#spring.data.redis.timeout=3000ms
#
#permission.init=true