#spring.application.name=greenlab
#server.servlet.context-path=/api-admin
#server.port=8081
#admin=1
#
#msc_user=bvnamhoc.namph,linhpt,phuonghoa,thucanh
#technician_user=DUNGNT,thuhant
#
#spring.data.mongodb.uri=mongodb://dev:1RDvrdLf@47.242.60.211:27017/greenlab
#spring.datasource.url=jdbc:mysql://14.177.64.56:33079/greenlab
#spring.datasource.username=dev
#spring.datasource.password=9VRcrdT
#
## spring.data.mongodb.uri=mongodb://localhost:27017/greenlab
## spring.datasource.url=jdbc:mysql://localhost:3307/greenlab
## spring.datasource.username=root
## spring.datasource.password=
#
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.servlet.multipart.max-file-size=10MB
#spring.servlet.multipart.max-request-size=10MB
#jwt.secret=ZmFrZVNlY3JldEtleUZvckdyZWVuTGFiMTIzNDU2Nzg5MDEyMzQ1Njc4OTA=
#jwt.expirationMs=86400000
#
#spring.data.redis.host=103.38.236.251
#spring.data.redis.port=6379
#spring.data.redis.password=NLoga41_1ABCCC123
#spring.data.redis.database=0
#spring.data.redis.timeout=3000ms
#
#permission.init=true

spring.application.name=greenlab
server.servlet.context-path=/api-admin
admin=1
server.port=8081
msc_user=bvnamhoc.namph,linhpt,phuonghoa,thucanh
technician_user=DUNGNT,thuhant
spring.data.mongodb.uri=mongodb://localhost:27018/greenlab
spring.datasource.url=jdbc:mysql://localhost:3307/greenlab
spring.datasource.username=dev
spring.datasource.password=552502102
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
jwt.secret=ZmFrZVNlY3JldEtleUZvckdyZWVuTGFiMTIzNDU2Nzg5MDEyMzQ1Njc4OTA=
jwt.expirationMs=86400000

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=NLoga41_1ABCCC123
spring.data.redis.database=0
spring.data.redis.timeout=3000ms

permission.init=true

# Social login - Google
spring.security.oauth2.client.registration.google.client-id=711480678320-fvcco1rgupkp38qgqpj5favp85orvmiq.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/oauth2/code/google

# TODO: Facebook
spring.security.oauth2.client.registration.facebook.client-id=1593186798803996
spring.security.oauth2.client.registration.facebook.client-secret=28f9a19ca342d200862e85cb6aefee52
spring.security.oauth2.client.registration.facebook.scope=email,public_profile
spring.security.oauth2.client.registration.facebook.redirect-uri={baseUrl}/oauth2/code/facebook
spring.security.oauth2.client.provider.facebook.authorization-uri=https://www.facebook.com/v18.0/dialog/oauth
spring.security.oauth2.client.provider.facebook.token-uri=https://graph.facebook.com/v18.0/oauth/access_token
spring.security.oauth2.client.provider.facebook.user-info-uri=https://graph.facebook.com/me?fields=id,name,email,picture

# Social login - GitHub
spring.security.oauth2.client.registration.github.client-id=Ov23liLxVQ4vZvqX3Xb9

spring.security.oauth2.client.registration.github.client-secret=8abcfa1a0d9d791b09d22c600790e79c9c26924d
spring.security.oauth2.client.registration.github.scope=read:user,user:email
spring.security.oauth2.client.registration.github.redirect-uri={baseUrl}/oauth2/code/github

# Social login - X (Twitter)
spring.security.oauth2.client.registration.twitter.client-id=1893871161139945472-sKU21uoMXX8xRdgCblIVCsRE2DhF6R
spring.security.oauth2.client.registration.twitter.client-secret=jBR4bcIvdFBzw1szPgvx2hLGLL22v4ONfhhDPN1tJkt4m
#spring.security.oauth2.client.registration.twitter.client-authentication-method=client_secret_basic
spring.security.oauth2.client.registration.twitter.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.twitter.redirect-uri={baseUrl}/oauth2/code/twitter
spring.security.oauth2.client.registration.twitter.scope=users.read,tweet.read


spring.security.oauth2.client.provider.twitter.authorization-uri=https://twitter.com/i/oauth2/authorize
spring.security.oauth2.client.provider.twitter.token-uri=https://api.twitter.com/2/oauth2/token
spring.security.oauth2.client.provider.twitter.user-info-uri=https://api.twitter.com/2/users/me

spring.security.oauth2.client.provider.twitter.user-name-attribute=data
spring.security.oauth2.client.registration.twitter.client-authentication-method=client_secret_post